nodeLinker: node-modules

npmRegistries:
  "https://npm.pkg.github.com/":
    npmAuthToken: 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

npmScopes:
  svaldivia:
    npmRegistryServer: "https://npm.pkg.github.com/"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
